### ISSUE TITLE
don't introspect undecorated classes

### ISSUE THREAD

**Issue by nzjrs** [sdvillal/whatami#9]
I got hit by this again and think it is too unexpected.

whatami should only poke around inside classes that have been decorated with @whatable. Doing otherwise risks unpleasant side-effects.

**Comment by sdvillal** [comment]
I agree, that behavior is too aggressive. I have changed it in b651dcff7 and now, for values that are objects without a proper representation, whatami represents them by 'Whatever()'.

I have published the fix to pypi, so just ```pip install --upgrade``` should give you the fix. Let me know if you have more use cases that are not covered.
